added my builder profile
BuidlGuidl/batch10.buidlguidl.com pull request #11
Opened 2024-10-15 21:13 UTC by Superior212

## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:0x62CeF3Ca8b52a9C69a17236CA2c56Cdb7a383E8e

2024-10-15 21:15 UTC, Superior212 commented
![Uploading Screenshot 2024-10-15 at 10.14.21 PM.png…]()
builder profile

2024-10-16 13:37 UTC, phipsae requested changes
Thank you very much for your personal page! It's simple, but looks great :)

Regarding the PR description please don't forget to relate to the respective issue (see https://gist.github.com/ZakGriffith/69d1eb8baebddd7d370b87a65a7e3ec0).

Please ensure that you don’t push changes to files unrelated to this PR. You can find my comments below.

2024-10-16 13:37 UTC, phipsae commented on packages/hardhat/contracts/BatchRegistry.sol
Please ensure that you do not modify the file.

2024-10-16 13:37 UTC, phipsae commented on packages/hardhat/contracts/CheckIn.sol
Pls make sure you don't push this file.

2024-10-16 13:37 UTC, phipsae commented on packages/hardhat/deploy/00_deploy_your_contract.ts
Please ensure that you do not modify the file.

2024-10-16 13:37 UTC, phipsae commented on packages/hardhat/hardhat.config.ts
Please ensure that you do not modify the file.

2024-10-16 13:37 UTC, phipsae commented on packages/nextjs/.env.example
Please ensure that you do not modify the file.

2024-10-16 13:37 UTC, phipsae commented on packages/nextjs/contracts/deployedContracts.ts
Please ensure that you do not modify the file.

2024-10-16 13:37 UTC, phipsae commented on packages/nextjs/scaffold.config.ts
Please ensure that you do not modify the file.

2024-10-16 13:37 UTC, phipsae commented on packages/nextjs/app/builders/0x62CeF3Ca8b52a9C69a17236CA2c56Cdb7a383E8e/page.tsx
> +import { Github, Linkedin, Twitter } from "lucide-react";
I'm receiving a deprecation warning for lucide-react. You may want to consider exploring an alternative library.

2024-10-16 13:37 UTC, phipsae commented on packages/nextjs/app/builders/0x62CeF3Ca8b52a9C69a17236CA2c56Cdb7a383E8e/page.tsx
> +            </a>
Since you are repeating yourself, you could create a social links array and use a map function.

2024-10-16 13:47 UTC, phipsae requested changes
an additional comment below.

2024-10-16 15:46 UTC, Superior212 commented
@derrekcoleman @phipsae fixed the issues Kindly assist me to check it out

2024-10-16 17:40 UTC, derrekcoleman requested changes
@Superior212, it's looking great! I'm following up on @phipsae's request to keep your PR focused and clean: each pull request should only do one thing, so a few files that were (accidentally?) included in your commits should be removed before we merge.

The main goal of the batch is to practice your collaboration and "git-fu" 🥷, so let us know if you would like any guidance using `git rebase`, `git push --force`, and other ways of manipulating the git history.

2024-10-16 17:40 UTC, derrekcoleman commented on packages/hardhat/.env.example
Remove file from PR. Out of scope for profile page

2024-10-16 17:40 UTC, derrekcoleman commented on packages/hardhat/contracts/BatchRegistry.sol
Remove file from PR. Out of scope for profile page

2024-10-16 17:40 UTC, derrekcoleman commented on packages/nextjs/.env.example
Remove file from PR. Out of scope for profile page

2024-10-16 17:50 UTC, Superior212 commented
@derrekcoleman removed files

2024-10-17 13:35 UTC, phipsae requested changes
In the beginning it can be challenging at first to contribute to repos, that's why we are having this course :) 
As @derrekcoleman mentioned, it's crucial to keep the codebase intact and only add or modify the files necessary for your PR to implement the specific feature.

Please review the comments below and ensure that no code is deleted from the main branch, as we need this parts.

2024-10-17 13:35 UTC, phipsae commented on packages/hardhat/.env.example
It looks like the entire file was deleted. We want to keep it as it was in the original main branch.

2024-10-17 13:35 UTC, phipsae commented on packages/hardhat/contracts/BatchRegistry.sol
It looks like the entire file was deleted. We want to keep it as it was in the original main branch.

2024-10-17 13:35 UTC, phipsae commented on packages/nextjs/.env.example
It looks like the entire file was deleted. We want to keep it as it was in the original main branch.

2024-10-17 13:35 UTC, phipsae commented on packages/nextjs/package.json
> +    "lucide-react": "^0.453.0",
Since you are not using "lucide-react" anymore, we don't need it here anymore.

2024-10-17 13:35 UTC, phipsae commented on packages/nextjs/package.json
> +    "react-icons": "^5.3.0",
Since you are not using "lucide-react" anymore, we don't need it here anymore.

2024-10-17 13:38 UTC, Superior212 commented on packages/nextjs/.env.example
i was asked to remove it by @derrekcoleman

2024-10-17 14:17 UTC, Superior212 commented
@phipsae, please check it now, i have made the changes

2024-10-17 20:56 UTC, phipsae requested changes
@Superior212 we are almost there! 

See my comments below.

2024-10-17 20:56 UTC, phipsae commented on yarn.lock
Since you only installed ```react-icons``` that should be the only thing that is added in here.

2024-10-17 20:56 UTC, phipsae commented on package-lock.json
This file doesn't belong here. Please ensure you use ```yarn``` instead of ```npm```.

2024-10-17 21:14 UTC, Superior212 commented on yarn.lock
@phipsae @derrekcoleman  fixed the issue hope no other issue :)

2024-10-18 16:10 UTC, phipsae commented on package.json
> +    "@types/react": "^18.3.5",
These are not needed here, as they belong and are in the nextjs folder package.json.

2024-10-18 16:10 UTC, phipsae commented on package.json
> +    "react-icons": "^5.3.0"
These are not needed here, as they belong and are in the nextjs folder package.json.

2024-10-18 16:33 UTC, Superior212 commented
@phipsae @derrekcoleman have removed the packages from the fille

2024-10-18 16:57 UTC, Superior212 commented
@phipsae can I also start working on other issues immediately after this is merged?
I have updated it and it doesn't have any of my commit on the nextjs

2024-10-18 17:03 UTC, phipsae commented
@Superior212 can you please run once more yarn install and push?

2024-10-18 17:09 UTC, Superior212 commented
@phipsae done 
thank you

2024-10-18 17:23 UTC, phipsae commented
Finally we can merge!!! 🎉 Thank for your patience and page! :)

2024-10-18 17:23 UTC, Superior212 commented
Thank you, so i can proceed with other issues

2024-10-18 17:23 UTC, merged