9-personal-page
BuidlGuidl/batch10.buidlguidl.com pull request #14
Opened 2024-10-17 10:50 UTC by Lukman-01

## Description
Added avater picture to public folder
Added personal profile page
![final](https://github.com/user-attachments/assets/2aa4f445-83bc-4eb5-97f1-80e7cc77fb91)

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address: 0x186a761645f2A264ad0A655Fb632Ca99150803A9

2024-10-18 18:11 UTC, phipsae requested changes
Thanks for the page, looks good!

Below you'll find some comments!

2024-10-18 18:11 UTC, phipsae commented on packages/nextjs/public/avater.jpeg
You could create a specific folder for you and name the image after your name. Otherwise we will file collusion, if everyone would name their picture avatar.

2024-10-18 18:11 UTC, phipsae commented on packages/nextjs/app/builders/0x186a761645f2A264ad0A655Fb632Ca99150803A9/page.tsx
> +    <div className="min-h-screen bg-blue-100 py-12 px-4 sm:px-6 lg:px-8">
You could consider to implement a dark mode for your page.

2024-10-18 18:11 UTC, phipsae commented on packages/nextjs/app/builders/0x186a761645f2A264ad0A655Fb632Ca99150803A9/page.tsx
> +              { name: "Twitter", url: "https://x.com/Icon_70" },
For better readability you could have a separate array outside.

2024-10-21 07:13 UTC, Lukman-01 commented
Good morning Sir, I have implemented all the corrections.

2024-10-21 12:39 UTC, phipsae requested changes
@Lukman-01, thanks looking all good! 
Just a little comment below and then it will be merged. 

Good start to the week!

2024-10-21 12:39 UTC, phipsae commented on packages/nextjs/public/Images/LukmansAvater.jpeg
Just a little comment here, remember to use lowercase letters for the naming convention, and consider naming the folder something like 'lukmansImages'

2024-10-21 16:44 UTC, Lukman-01 commented on packages/nextjs/public/Images/LukmansAvater.jpeg
@phipsae Thank you sir, I have implemented the correct naming convention.

2024-10-22 13:37 UTC, Lukman-01 commented
Good afternoon Sir @phipsae, I have make the necessary changes.

2024-10-22 21:15 UTC, phipsae commented
Thanks a lot! It's merged!

2024-10-22 21:16 UTC, merged