feat: implemented personal builder profile page
BuidlGuidl/batch10.buidlguidl.com pull request #16
Opened 2024-10-18 12:12 UTC by michojekunle

## Description
Implemented personal builder profile page, that shows my details, my avatar, a short bio and my address

## Additional Information
- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address: 0x7429CbD5eD20736645723E972bE60B7F6BF5959c

![image](https://github.com/user-attachments/assets/982afee9-1633-478c-bbff-bc11aa7c26c7)

2024-10-18 12:14 UTC, michojekunle commented
@phipsae @technophile-04 made this PR as regards this issue https://github.com/BuidlGuidl/batch10.buidlguidl.com/issues/9

**please review**

2024-10-18 17:53 UTC, phipsae requested changes
@michojekunle thanks for the page! You really like that you integrate the particles effect :)

Below you'll find comments regarding the code. If there are any questions feel free to ask. 

Thanks!

2024-10-18 17:53 UTC, phipsae commented on package-lock.json
We don't want the package-lock.json file, as we use yarn. So please remove this file.

2024-10-18 17:53 UTC, phipsae commented on packages/nextjs/public/assets/dvm0x742_avatar.jpg
Here you could also name the folder after your name, so you have a dedicated folder for your page.

2024-10-18 17:53 UTC, phipsae commented on packages/nextjs/app/builders/0x7429CbD5eD20736645723E972bE60B7F6BF5959c/page.tsx
> +import { Check, Code, Copy, Cpu, Github, Globe, Linkedin, Twitter } from "lucide-react";
For Github, LinkedIn, Twitter it gives me deprecated warning. Maybe you want to consider to change to another library, like react icons.

2024-10-18 17:53 UTC, phipsae commented on yarn.lock
The only code change should be the addition of "lucide-react."

2024-10-18 17:53 UTC, phipsae commented on packages/nextjs/app/builders/0x7429CbD5eD20736645723E972bE60B7F6BF5959c/page.tsx
> +                  </span>
You might consider using the SE2 component Address to leverage the existing component. There you already have the copy functionality.

2024-10-18 17:53 UTC, phipsae commented on packages/nextjs/app/builders/0x7429CbD5eD20736645723E972bE60B7F6BF5959c/page.tsx
> +    <div className="relative min-h-screen overflow-hidden bg-gradient-to-br from-base-200 to-base-300">
Your Floating Particles work perfectly in light mode. 
But in dark mode you cannot see it, so you might adapt that.

2024-10-18 17:53 UTC, phipsae commented on packages/nextjs/app/builders/0x7429CbD5eD20736645723E972bE60B7F6BF5959c/page.tsx
In my console when I load your page I get the following error, please fix it. 
It has to do with Parallax Background and Floating Particles.
<img width="504" alt="Screenshot 2024-10-18 at 13 47 11" src="https://github.com/user-attachments/assets/2301349c-24df-424e-81a2-a2d40e047cfd">

2024-10-19 12:10 UTC, michojekunle commented
Hi @phipsae Thank you so much for your review, I've made the necessary and suggested changes as specified in the comments, and I also learnt new stuff regarding disabling SSR for client pages.

Please review 🙌🏾

> @michojekunle thanks for the page! You really like that you integrate the particles effect :)
> 
> Below you'll find comments regarding the code. If there are any questions feel free to ask.
> 
> Thanks!

Hi @phipsae Thank you so much for your review, I've made the necessary and suggested changes as specified in the comments, and I also learnt new stuff regarding disabling SSR for client pages.

Please review 🙌🏾

2024-10-21 13:13 UTC, phipsae requested changes
Works and great! 

Just a little change and then we are good to go merging. 

Thanks!

2024-10-21 13:33 UTC, michojekunle commented on packages/nextjs/app/builders/0x7429CbD5eD20736645723E972bE60B7F6BF5959c/page.tsx
> +export default DevvMichaelProfile;
Alright, Awesome, I'm on it

2024-10-21 13:37 UTC, michojekunle commented on packages/nextjs/app/builders/0x7429CbD5eD20736645723E972bE60B7F6BF5959c/page.tsx
> +export default DevvMichaelProfile;
Hi @phipsae, Thank you so much for the review. I've implemented the changes

2024-10-21 14:32 UTC, phipsae commented
Very nice, thank you a lot!!! 
Gonna merge it!

2024-10-21 14:32 UTC, merged