Fetch and Display Builder Count from BatchRegistry Contract
BuidlGuidl/batch10.buidlguidl.com pull request #17
Opened 2024-10-18 20:30 UTC by Superior212

## Description

This pull request addresses the display of the number of builders who have checked into the contract within the `packages/nextjs/app/page.tsx` file. Currently, a placeholder string "To Be implemented" is displayed, which does not provide any useful information to users. 

### Proposed Changes
- Replace the placeholder string with the actual count of builders who have checked in, which will be retrieved from the `BatchRegistry` contract.
- Implement a method to fetch this count and ensure it updates dynamically when the data changes.

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

_Closes #5

Address:0x62CeF3Ca8b52a9C69a17236CA2c56Cdb7a383E8e

2024-10-21 14:07 UTC, phipsae requested changes
Thanks for the implementation!
Below you'll find some comments. 
Let me know if something is not clear.

2024-10-21 14:07 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +  }
Instead of having this "skeleton" you might handle the loading inline in renderContent

2024-10-21 14:07 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +  const [counter, setCounter] = useState<number | undefined>();
We don't need a state here, we can use the counter directly in the render (see comment below).

2024-10-21 14:07 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +    data,
You want to name data like, data or checkedInCounter.

2024-10-21 14:07 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +  const renderContent = () => {
Maybe give it a more descriptive name.

2024-10-21 14:07 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +        <span>{counter !== undefined ? counter : "0"}</span>
Here you could conditionally render counter/checkedInCounter

2024-10-22 21:38 UTC, phipsae requested changes
Thanks for the adjustments! 
Just a little thing to change, see below.

2024-10-22 21:38 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +    }
I think this might be not needed, you could conditionally render in line 39 instead.

2024-10-22 21:38 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +        <span>{checkedInCounter !== undefined ? Number(checkedInCounter) : "0"}</span>
having contractLoading here might work as well

2024-10-23 12:54 UTC, Superior212 commented
@phipsae have made the adjustment. I hope we are good to go.

2024-10-23 19:54 UTC, phipsae requested changes
Just a little thing to change and then we are good to go.

2024-10-23 19:54 UTC, phipsae commented on packages/nextjs/app/page.tsx
Always make sure to check the console.log.
Here I am getting the error: 

<img width="557" alt="Screenshot 2024-10-23 at 15 50 53" src="https://github.com/user-attachments/assets/be5b4e3c-9b5b-4658-86aa-31d9be00ba77">

So make sure not to have `<p>`

2024-10-23 20:02 UTC, Superior212 commented on packages/nextjs/app/page.tsx
@phipsae fixed kindly check

2024-10-23 20:02 UTC, Superior212 commented
@phipsae have remove the <p> tag

2024-10-23 20:17 UTC, phipsae commented
Thank you! So let's merge!

2024-10-23 20:17 UTC, merged