Feat builder profile
BuidlGuidl/batch10.buidlguidl.com pull request #18
Opened 2024-10-19 17:45 UTC by pbkompasz

## Description

Builder profile with a short description, and links to socials e.g. Discord, GitHub, etc.

![Screenshot from 2024-10-19 19-38-16](https://github.com/user-attachments/assets/5ecf7ec6-153c-4deb-97c4-9f179dafeeae)

## Additional Information
- [X] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [X] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

Closes #9

Your ENS/address: 0x26BfbD8ED2B302ec2c2B6f063C4caF7abcB062e0

2024-10-21 14:24 UTC, phipsae requested changes
@pbkompasz, thanks for the page! 

You could improve it further with the suggestions below.

When you are working on issues it is a good practice to name your branch with the respective issue number.

2024-10-21 14:24 UTC, phipsae commented on packages/nextjs/app/builders/0x26BfbD8ED2B302ec2c2B6f063C4caF7abcB062e0/page.tsx
> +            <p>Address: 0x26BfbD8ED2B302ec2c2B6f063C4caF7abcB062e0</p>
There is a nice SE2 address component, you might want to use this one instead of just a blank address.

2024-10-21 14:24 UTC, phipsae commented on packages/nextjs/app/builders/0x26BfbD8ED2B302ec2c2B6f063C4caF7abcB062e0/page.tsx
> +            </p>
You could consider to highlight some words in here, to make it more readable.

2024-10-23 18:32 UTC, pbkompasz commented
@phipsae Cleaned up the bio and added the `Address` component.

2024-10-23 20:37 UTC, phipsae commented
Thanks @pbkompasz! The page is good to go and merged.

2024-10-23 20:37 UTC, merged