9 personal page
BuidlGuidl/batch10.buidlguidl.com pull request #19
Opened 2024-10-19 17:52 UTC by Michael-Nwachukwu

## Description

Created private folder for images in public folder and moved all images used to the folder. - (folder name : michaelNwachukwu-images).
Added personal profile page.

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

My address: 0x5defa248834d4b6112a0Ad3854AA22913e01BD83

2024-10-21 14:48 UTC, phipsae requested changes
Thanks for the changes you are already made! 

Below just tiny comments and then we are good to go to merge.

2024-10-21 14:48 UTC, phipsae commented on packages/nextjs/app/builders/0x5defa248834d4b6112a0Ad3854AA22913e01BD83/page.tsx
> +        </p>
Maybe some highlighting would be nice.

2024-10-23 22:57 UTC, Michael-Nwachukwu commented
Thanks for the recommended changes @phipsae I have applied them accordingly, please take a look. 🙂

2024-10-24 13:49 UTC, phipsae requested changes
Thanks for the changes! It looks good.

Just a quick note: we’re using Yarn as our package manager, so it’s best to avoid running `npm install`.

See comments below.

2024-10-24 13:49 UTC, phipsae commented on package-lock.json
We don't want to have this file, since we are using yarn and not npm.

2024-10-24 13:49 UTC, phipsae commented on yarn.lock
Here shouldn't be any changes, since I think you don't install any new libraries (react icons should be already installed in the main branch).

2024-10-24 13:49 UTC, phipsae commented on packages/nextjs/app/builders/0x5defa248834d4b6112a0Ad3854AA22913e01BD83/components/Socials.tsx
> +const Socials = () => {
Since we are using typescript, you might want to give the component a type.

2024-10-25 20:04 UTC, Michael-Nwachukwu commented
Thanks for pointing that out @phipsae  
All done now

2024-10-28 17:42 UTC, phipsae requested changes
Just ensure there are no modifications to the yarn.lock file, and then we’re ready to merge!

2024-10-28 17:42 UTC, phipsae commented on yarn.lock
Pleases, no changes to this file.

2024-10-31 14:05 UTC, phipsae commented
Perfect, thanks! Lets merge

2024-10-31 14:06 UTC, merged