Added member status to the home page
BuidlGuidl/batch10.buidlguidl.com pull request #24
Opened 2024-10-25 09:17 UTC by Lukman-01

## Description

 I added batch member status and if checked in status to the home page

![MemberStatus](https://github.com/user-attachments/assets/45d1b0aa-f5f9-4926-938c-4dc5faa7a61f)

Your ENS/address: 0x186a761645f2A264ad0A655Fb632Ca99150803A9

2024-10-25 15:05 UTC, derrekcoleman commented
Thank you for the PR, @Lukman-01!

First, let's make the PR description even nicer. I love your use of screenshot to show the implementation. Could you add a couple more screenshots for the other possible states? 
- Wallet not connected at all
- Wallet connected, not part of the Batch
- Wallet connected, part of the Batch, not checked in yet (you can mock this locally even though you already checked in in "production" on OP mainnet)
The issue you're solving is about providing a clear UX for the user based on these possible states, so that would be very useful information to help us understand how you're thinking about it.

Could you also update your PR description to link to issue #5 ? Not only is that useful context, it also makes it so that when this PR gets merged the matching issue is automatically closed as well.

2024-10-25 20:25 UTC, Lukman-01 commented
Thank you @derrekcoleman for the observation. Instead of doing screenshot for each implementation, I made a short clip demostrating each implementation. I hope it covers every implementation needed.

https://www.loom.com/share/4e7125956a8f481ebef43f1847e5d119?sid=466dfe05-23a5-4283-a8b8-e3498dad428c

kindly check the above link for the demostration.

2024-10-28 06:58 UTC, Lukman-01 commented
Good morning Sir @derrekcoleman, kindly review if there will be any changes I need to make.

2024-10-29 17:49 UTC, phipsae requested changes
Thanks for the PR!!!

See below my comments.

2024-10-29 17:49 UTC, phipsae commented on packages/nextjs/app/page.tsx
How about displaying just one status? If I'm not on the allowlist, is it necessary to inform me that I haven't checked in? 

Perhaps we could add a status indicating that the wallet isn’t connected, so users know they need to connect it to view their status, as @derrekcoleman suggested?

2024-10-31 19:46 UTC, Lukman-01 commented
Good day @derrekcoleman, @phipsae, I have Implemented all cases required for the membership status. 

![1](https://github.com/user-attachments/assets/f6e3eb9b-1890-4701-8158-3ebd66c5b172)
![2](https://github.com/user-attachments/assets/d461c8e5-7f33-4f58-b95c-92b858dd3093)
![3](https://github.com/user-attachments/assets/94a9fb5e-8485-40f1-bb76-df4570db86af)

As for the last one(if a member but have not checkedIn), together with afformentioned ones above are demostrated in the clip below

https://www.loom.com/share/996b3e853d9b46e2ac2814569bdacc5c?sid=4dea6659-620b-482f-b18d-36a1a718852a

2024-11-01 12:04 UTC, phipsae requested changes
I like it, thanks for the implementation!

Just a couple of little comments to work on, shouldn't be too much. And then we merge.

2024-11-01 12:04 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +  userContractAddress: string;
Do we need userContractAddress or is connectedAddress enough?

2024-11-01 12:04 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +          Active with contract: {userContractAddress?.slice(0, 6)}...{userContractAddress?.slice(-4)}
Here you might want to use the SE2 component `<Address>`

2024-11-01 16:02 UTC, Lukman-01 commented
Thank you Sir @phipsae, corrections implemented.

2024-11-03 13:45 UTC, phipsae requested changes
There's just a small error that needs to be fixed before we can merge. 

Thanks!

2024-11-03 13:45 UTC, phipsae commented on packages/nextjs/app/page.tsx
> +        </p>
There’s a hydration error occurring. Please make sure to always check your console for any potential errors. 
<img width="482" alt="Screenshot 2024-11-03 at 10 41 45" src="https://github.com/user-attachments/assets/ed5de89c-8c01-406b-9dcf-2a18d868290b">

2024-11-03 18:37 UTC, Lukman-01 commented
Thank you very much Sir, I will be more observant of the console now. The issue has been resolved.

![resolve](https://github.com/user-attachments/assets/6d932ce2-c829-4ba6-ae49-e8ed69b3c932)

2024-11-04 13:06 UTC, phipsae commented
Perfect, thanks for your work! Let's merge.

2024-11-04 13:06 UTC, merged