feat: cherry's builder profile
BuidlGuidl/batch10.buidlguidl.com pull request #25
Opened 2024-10-28 07:23 UTC by aspiringLilCoder

## Description

Built a simple builder profile with profile picture, description, social links, and address.

![image](https://github.com/user-attachments/assets/7b78ca09-0b9a-4da2-8ece-d5796dc6a2f3)

## Additional Information

- [/ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ /] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{9}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: 0xC52E3E454a735d4A74F3dd6Ea281F7AebDFAad83

2024-10-29 18:09 UTC, phipsae requested changes
Thank you a lot for your personal page!

As a tip: it might be helpful to name your branch after the issue you’re addressing.

Below you'll find some comments.

2024-10-29 18:09 UTC, phipsae commented on packages/nextjs/app/builders/0xC52E3E454a735d4A74F3dd6Ea281F7AebDFAad83/page.tsx
> +            stroke-width="2"
Please remember to check your browser console.  It's currently showing me the following error:

<img width="513" alt="Screenshot 2024-10-29 at 14 58 06" src="https://github.com/user-attachments/assets/020b5272-6176-4188-8c0b-3b3af8dec351">

2024-10-29 18:09 UTC, phipsae commented on packages/nextjs/app/builders/0xC52E3E454a735d4A74F3dd6Ea281F7AebDFAad83/page.tsx
> +const PersonalPage: NextPage = () => {
You might want to give a more descriptive name to the page, since there are more builder pages.

2024-10-29 18:09 UTC, phipsae commented on packages/nextjs/app/builders/0xC52E3E454a735d4A74F3dd6Ea281F7AebDFAad83/page.tsx
> +        <a
For a cleaner code base you might want to create an array with your social links and use a map function to render it.

2024-10-31 00:32 UTC, phipsae requested changes
Thanks for implementing the changes so fast! 
Let's only make the code a little bit cleaner and then we merge. 

See the comment below.

2024-10-31 00:32 UTC, phipsae commented on packages/nextjs/app/builders/0xC52E3E454a735d4A74F3dd6Ea281F7AebDFAad83/page.tsx
> +  ];
Do you come up with a solution how to reduce the redundant code in here?  ```<svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="#1A1A1A"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"```

2024-10-31 06:55 UTC, aspiringLilCoder commented
> Thanks for implementing the changes so fast! Let's only make the code a little bit cleaner and then we merge.
> 
> See the comment below.

Thank you for the quick feedback!

In my latest commit, I've implemented the following update:
✅Reduce redundant code by incorporating the svg tags in the map function

2024-10-31 14:02 UTC, phipsae commented
Nice, looks great! Lets merge!

2024-10-31 14:02 UTC, merged