9 personal page
BuidlGuidl/batch10.buidlguidl.com pull request #27
Opened 2024-11-06 01:24 UTC by emarc99

## Description

Build personal builder's page.

![image](https://github.com/user-attachments/assets/f139c638-2976-45cf-818f-0a774103cb74)

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address: emarc.eth

2024-11-09 03:03 UTC, phipsae requested changes
Thank you so much for submitting your PR for your personal page!

Just a quick note: please make sure that only the relevant files are added or changed. In your case that should be only `backgroundPattern.tsx`, `page.tsx`, and your picture. Any unrelated files should stay untouched. Once you've made these adjustments, I’ll review your page.

2024-11-10 22:18 UTC, emarc99 commented
I have applied requested changes.

2024-11-11 02:57 UTC, phipsae requested changes
Thanks for your nice personal page, like your background! 

Could you please pull the latest changes from the main branch and merge them into your branch? So you'll always ensure compatibility with the latest updates to the main branch.

Also, take a look at the little comments below. 
Once those are addressed, we’ll be ready to merge.

2024-11-11 02:57 UTC, phipsae commented on packages/nextjs/app/builders/0x11Bc455A4f64F800f9Ceb37614f02b213f98591d/page.tsx
> +      href: "https://discord.com/emarc99", // Can be your Discord username or server invite
Somehow the discord link doesn't work.

2024-11-11 02:57 UTC, phipsae commented on packages/nextjs/app/builders/0x11Bc455A4f64F800f9Ceb37614f02b213f98591d/page.tsx
> +  const socialLinks = [
You could have to `socialLinks` array outside of the component. It prevents unnecessary recreation on each render.

2024-11-11 02:57 UTC, phipsae commented on packages/nextjs/app/builders/0x11Bc455A4f64F800f9Ceb37614f02b213f98591d/page.tsx
> +            ENS/Wallet Address:<span className="font-bold text-2xl"> emarc.eth</span>
Here you could use the SE2 component `<Address>`

2024-11-13 03:51 UTC, emarc99 commented
Page is ready, thank you.

2024-11-13 04:17 UTC, phipsae commented
Thanks a lot for the page! Time to merge.

2024-11-13 04:17 UTC, merged