#7: Tweak the main page
BuidlGuidl/batch10.buidlguidl.com pull request #29
Opened 2024-11-13 23:54 UTC by kcmikee

## Description

This PR introduces the initial setup for the homepage layout and design updates. After discussions with team members, we've decided on a clean and minimalistic approach that aligns with our app's simplicity and functionality. The focus is on a lightweight and user-friendly interface, maintaining fast load times.

Changes Implemented:
Updated the homepage structure with a more organised layout.
Ensured the design is responsive and maintains consistency across different devices.

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes Issue: https://github.com/BuidlGuidl/batch10.buidlguidl.com/issues/7 (Tweak The Home Page) 

Your ENS/address: 0x8Bb563DC969cC3b3e7275474c3847b44dBCB9441

https://github.com/user-attachments/assets/258672b4-6a6a-4e8d-83c9-f754725c4dba

2024-11-21 08:12 UTC, phipsae requested changes
Very very nice landing page, thanks a lot! I really love it.

Just a little of changes and we can merge this beautiful merge. 

Thanks!

2024-11-21 08:12 UTC, phipsae commented on packages/nextjs/app/page.tsx
In light mode, the text is hard to read. 

<img width="706" alt="Screenshot 2024-11-21 at 16 08 54" src="https://github.com/user-attachments/assets/dbff43c0-37ef-4e10-bd2b-47b63eeae60b">

2024-11-21 08:12 UTC, phipsae commented on packages/nextjs/components/StarsBg.tsx
Resizing the window throws the following error in the console. 
The error you're seeing is likely related to trying to access the canvas context after the component has been unmounted or when the canvas reference is null.

<img width="341" alt="Screenshot 2024-11-21 at 16 10 08" src="https://github.com/user-attachments/assets/40c625cc-8f6e-4628-b821-323a60e8328b">

2024-11-21 10:34 UTC, kcmikee commented on packages/nextjs/components/StarsBg.tsx
Noted, I'll look into it

2024-11-24 01:36 UTC, phipsae commented
Very nice work! It's merged :)

2024-11-24 01:36 UTC, merged